version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ecommerce-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce-network

  # Optional: Redis for queue
  # redis:
  #   image: redis:7-alpine
  #   container_name: ecommerce-redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - ecommerce-network

volumes:
  mongodb_data:
  # redis_data:

networks:
  ecommerce-network:
    driver: bridge
